[project]
name = "termpdf"
version = "0.1.0"
description = "A simple PDF-viewer to be used inside a compatible terminal"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.16.0",
    "pymupdf>=1.26.4",
    "term-image>=0.7.2",
    "watchdog>=6.0.0",
]
